In [2]:
import torch





In [3]:
my_tensor = torch.tensor([[4.0,1.0],[5.0,3.0],[6.0,2.0]])

print(my_tensor[:])
print(my_tensor[1:])
print(my_tensor[1:,:]) #recomendable
print(my_tensor[0,:])
print(my_tensor[-1,0])

tensor([[4., 1.],
        [5., 3.],
        [6., 2.]])
tensor([[5., 3.],
        [6., 2.]])
tensor([[5., 3.],
        [6., 2.]])
tensor([4., 1.])
tensor(6.)


In [4]:
a= torch.tensor([[1,2]], dtype=torch.int64)

print(a*3)

tensor([[3, 6]])


In [5]:
t_1 = torch.tensor([[2, 3, 4, 1]])
t_2= torch.tensor([[5, -2, 3, 7]])

t_1+t_2

tensor([[7, 1, 7, 8]])